name: Deploy bot
on:
  workflow_dispatch:
env:
  REPO_NAME: ${{ github.event.repository.name }}
jobs:
  Install-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Docker ${{ env.REPO_NAME }}
        uses: fifsky/ssh-action@master
        with:
          command: |
            sudo apt-get update
          host: 144.202.9.135
          user: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}

  Deploy-bot:
    needs: [ Install-docker ]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy bot ${{ env.REPO_NAME }}
        uses: fifsky/ssh-action@master
        with:
          command: |
            sudo docker image pull ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_HUB_REPO }}:${{ secrets.VERSION }}
            sudo docker run -e TOKEN="${{ secrets.BOT_TOKEN }}" CLIENT_ID=${{ secrets.BOT_CLIENT_ID }}  ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_HUB_REPO }}:${{ secrets.VERSION }}
          host: 144.202.9.135
          user: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}