name: Docker Iamge CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        DOCKER_REPO: ${{ secrets.DOCKER_HUB_REPO }}
        TEST: "test"

    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: test variables
        run: echo "::debug::Set the variable to ${{ env.TEST }} and ${{ env.DOCKER_REPO}}"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_USER }}/${{ env.DOCKER_REPO }}:latest
