name: Docker Iamge CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.1.0
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCER_REPO: ${{ secrets.DOCKER_HUB_REPO }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$DOCKER_REPO:$(date +%s)
    - name: Docker Push
      run: docker push $DOCKER_USER/$DOCKER_REPO