name: Docker Iamge CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        DOCER_REPO: ${{ secrets.DOCKER_HUB_REPO }}

    steps:
    - uses: actions/checkout@v3.1.0
    - name: Login to Docker Hub
      run: echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$DOCKER_REPO:$(date +%s)
    - name: Docker Push
      run: docker push $DOCKER_USER/$DOCKER_REPO